// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecom.Data;

#nullable disable

namespace ecom.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240426092024_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ecom.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Kolekcionarstvo",
                            Keywords = "kolekcije,kolekcija",
                            Name = "Kolekcionarstvo",
                            Note = ""
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Numizmatika",
                            Keywords = "novac",
                            Name = "Numizmatika",
                            Note = ""
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Antikviteti",
                            Keywords = "starine",
                            Name = "Antikviteti",
                            Note = ""
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Umjetnost",
                            Keywords = "umjetnine",
                            Name = "Umjetnost",
                            Note = ""
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Knjige i tisak",
                            Keywords = "",
                            Name = "Knjige-tisak",
                            Note = ""
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Glazba i film",
                            Keywords = "",
                            Name = "Glazba-film",
                            Note = ""
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Audio / video",
                            Keywords = "multimedija,av tehnika, audio video tehnika, audio i video tehnika,a/v tehnika",
                            Name = "Audio-video",
                            Note = ""
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Računala i mobiteli",
                            Keywords = "",
                            Name = "Racunala-mobiteli",
                            Note = ""
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "Konzole i igrice",
                            Keywords = "igrice",
                            Name = "Konzole-igrice",
                            Note = ""
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "Odjeća i obuća",
                            Keywords = "",
                            Name = "Odjeca-obuca",
                            Note = ""
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "Nakit i satovi",
                            Keywords = "",
                            Name = "Nakit-satovi",
                            Note = ""
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "Modni dodaci",
                            Keywords = "accessories",
                            Name = "Modni-dodaci",
                            Note = ""
                        },
                        new
                        {
                            Id = 13,
                            DisplayName = "Ljepota i zdravlje",
                            Keywords = "",
                            Name = "Ljepota-zdravlje",
                            Note = ""
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "Sport i oprema",
                            Keywords = "sportska oprema",
                            Name = "Sport-oprema",
                            Note = ""
                        },
                        new
                        {
                            Id = 15,
                            DisplayName = "Dom i vrt",
                            Keywords = "za kuću,za kucu,za dom,kuća,stan,kuca",
                            Name = "Dom-vrt",
                            Note = ""
                        },
                        new
                        {
                            Id = 16,
                            DisplayName = "Igre i igračke",
                            Keywords = "igracke",
                            Name = "Igre-igracke",
                            Note = ""
                        },
                        new
                        {
                            Id = 17,
                            DisplayName = "Škola i posao",
                            Keywords = "",
                            Name = "Skola-posao",
                            Note = ""
                        },
                        new
                        {
                            Id = 18,
                            DisplayName = "Ostalo",
                            Keywords = "",
                            Name = "Ostalo",
                            Note = "Predmeti koji nemaju posebnu kategoriju."
                        });
                });

            modelBuilder.Entity("ecom.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ecom.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuctionStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasExtraPictures")
                        .HasColumnType("bit");

                    b.Property<string>("ImagesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdvertised")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEndTimeAdjusted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStartTimeAdjusted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferCount")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ecom.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DisplayName = "Militarija",
                            Keywords = "",
                            Name = "Militarija",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DisplayName = "Filatelija",
                            Keywords = "",
                            Name = "Filatelija",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DisplayName = "Figurice",
                            Keywords = "figure",
                            Name = "Figurice",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DisplayName = "Sličice, karte i albumi",
                            Keywords = "slicice,kartice,igraće karte,igrace karte",
                            Name = "Slicice-karte-albumi",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DisplayName = "Razglednice",
                            Keywords = "",
                            Name = "Razglednice",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DisplayName = "Modeli i makete",
                            Keywords = "modelarstvo,maketarstvo,autići,autici,modeli auta",
                            Name = "Modeli-makete",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            DisplayName = "Suveniri",
                            Keywords = "",
                            Name = "Suveniri",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            DisplayName = "Privjesci",
                            Keywords = "privesci,privjesci za ključeve,privjesci za kljuceve",
                            Name = "Privjesci",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            DisplayName = "Ulaznice i karte",
                            Keywords = "",
                            Name = "Ulaznice-karte",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            DisplayName = "Telefonske kartice",
                            Keywords = "",
                            Name = "Telefonske-kartice",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            DisplayName = "Pehari i medalje",
                            Keywords = "trofeji,kolajne",
                            Name = "Pehari-medalje",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            DisplayName = "Registracijske tablice",
                            Keywords = "registracije,registarske tablice",
                            Name = "Registracijske-tablice",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            DisplayName = "Zastave",
                            Keywords = "zastavice",
                            Name = "Zastave",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            DisplayName = "Salvete",
                            Keywords = "salvetice",
                            Name = "Salvete",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            DisplayName = "Lotovi",
                            Keywords = "",
                            Name = "Lotovi",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            DisplayName = "Ostalo - kolekcionarstvo",
                            Keywords = "",
                            Name = "Ostalo-kolekcionarstvo",
                            ParentCategoryName = "Kolekcionarstvo"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            DisplayName = "Kovanice",
                            Keywords = "novčići,novcici",
                            Name = "Kovanice",
                            ParentCategoryName = "Numizmatika"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            DisplayName = "Novčanice",
                            Keywords = "novcanice",
                            Name = "Novcanice",
                            ParentCategoryName = "Numizmatika"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            DisplayName = "Bonovi",
                            Keywords = "",
                            Name = "Bonovi",
                            ParentCategoryName = "Numizmatika"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            DisplayName = "Žetoni",
                            Keywords = "",
                            Name = "Zetoni",
                            ParentCategoryName = "Numizmatika"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            DisplayName = "Ostalo - numizmatika",
                            Keywords = "",
                            Name = "Ostalo-numizmatika",
                            ParentCategoryName = "Numizmatika"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            DisplayName = "Keramika, porculan i staklo",
                            Keywords = "",
                            Name = "Keramika-porculan-staklo",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            DisplayName = "Stari namještaj",
                            Keywords = "starinski",
                            Name = "Stari-namjestaj",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            DisplayName = "Stari uređaji i aparati",
                            Keywords = "",
                            Name = "Stari-uredaji-aparati",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            DisplayName = "Stari pribor i oprema",
                            Keywords = "",
                            Name = "Stari-pribor-oprema",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            DisplayName = "Stara odjeća i obuća",
                            Keywords = "",
                            Name = "Stara-odjeca-obuca",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            DisplayName = "Stari nakit i satovi",
                            Keywords = "starinski nakit",
                            Name = "Stari-nakit-satovi",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            DisplayName = "Stare knjige i dokumenti",
                            Keywords = "",
                            Name = "Stare-knjige-dokumenti",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            DisplayName = "Ostalo - antikviteti",
                            Keywords = "",
                            Name = "Ostalo-antikviteti",
                            ParentCategoryName = "Antikviteti"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            DisplayName = "Umjetničke slike",
                            Keywords = "",
                            Name = "Umjetnicke-slike",
                            ParentCategoryName = "Umjetnost"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            DisplayName = "Fotografije",
                            Keywords = "",
                            Name = "Fotografije",
                            ParentCategoryName = "Umjetnost"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            DisplayName = "Ikone",
                            Keywords = "",
                            Name = "Ikone",
                            ParentCategoryName = "Umjetnost"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            DisplayName = "Skulpture",
                            Keywords = "",
                            Name = "Skulpture",
                            ParentCategoryName = "Umjetnost"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            DisplayName = "Gobleni",
                            Keywords = "",
                            Name = "Gobleni",
                            ParentCategoryName = "Umjetnost"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            DisplayName = "Ostalo - umjetnost",
                            Keywords = "",
                            Name = "Ostalo-umjetnost",
                            ParentCategoryName = "Umjetnost"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 5,
                            DisplayName = "Književnost",
                            Keywords = "",
                            Name = "Knjizevnost",
                            ParentCategoryName = "Knjige-tisak"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            DisplayName = "Znanost i enciklopedije",
                            Keywords = "",
                            Name = "Znanost-enciklopedije",
                            ParentCategoryName = "Knjige-tisak"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            DisplayName = "Atlasi i karte",
                            Keywords = "",
                            Name = "Atlasi-karte",
                            ParentCategoryName = "Knjige-tisak"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            DisplayName = "Magazini i časopisi",
                            Keywords = "",
                            Name = "Magazini-casopisi",
                            ParentCategoryName = "Knjige-tisak"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            DisplayName = "Stripovi",
                            Keywords = "",
                            Name = "Stripovi",
                            ParentCategoryName = "Knjige-tisak"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            DisplayName = "Dječja literatura",
                            Keywords = "",
                            Name = "Djecja-literatura",
                            ParentCategoryName = "Knjige-tisak"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            DisplayName = "Ostalo - tisak",
                            Keywords = "",
                            Name = "Ostalo-tisak",
                            ParentCategoryName = "Knjige-tisak"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 6,
                            DisplayName = "Glazbeni instrumenti",
                            Keywords = "muzički,instrumenti",
                            Name = "Glazbeni-instrumenti",
                            ParentCategoryName = "Glazba-film"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            DisplayName = "CDovi",
                            Keywords = "",
                            Name = "CDovi",
                            ParentCategoryName = "Glazba-film"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            DisplayName = "Audio kasete",
                            Keywords = "",
                            Name = "Audio-Kasete",
                            ParentCategoryName = "Glazba-film"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            DisplayName = "Gramofonske ploče",
                            Keywords = "",
                            Name = "Gramofonske-ploce",
                            ParentCategoryName = "Glazba-film"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            DisplayName = "DVD i BluRay",
                            Keywords = "",
                            Name = "DVD-BluRay",
                            ParentCategoryName = "Glazba-film"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 6,
                            DisplayName = "VHS",
                            Keywords = "",
                            Name = "VHS",
                            ParentCategoryName = "Glazba-film"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 6,
                            DisplayName = "Ostalo - glazba i film",
                            Keywords = "",
                            Name = "Ostalo-glazba-film",
                            ParentCategoryName = "Glazba-film"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 7,
                            DisplayName = "TV i oprema",
                            Keywords = "Televizori",
                            Name = "TV-oprema",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            DisplayName = "Fotoaparati i kamere",
                            Keywords = "",
                            Name = "Fotoaparati-kamere",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 7,
                            DisplayName = "Dronovi",
                            Keywords = "",
                            Name = "Dronovi",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 7,
                            DisplayName = "Radio i telefoni",
                            Keywords = "radioprijemnik,radioprijemnici",
                            Name = "Radio-telefoni",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 7,
                            DisplayName = "Zvučnici i pojačala",
                            Keywords = "zvučnik,pojačalo",
                            Name = "Zvucnici-pojacala",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 7,
                            DisplayName = "Linije i kasetofoni",
                            Keywords = "kazetofoni",
                            Name = "Linije-kasetofoni",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 7,
                            DisplayName = "Kućna kina i DVD playeri",
                            Keywords = "kućno kino",
                            Name = "Kucno-kino-dvd-playeri",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 7,
                            DisplayName = "MP3, walkmani, iPodi",
                            Keywords = "mp3 playeri",
                            Name = "MP3-walkman-ipod",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 7,
                            DisplayName = "Ostalo - audio / video",
                            Keywords = "",
                            Name = "Ostalo-audio-video",
                            ParentCategoryName = "Audio-video"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 8,
                            DisplayName = "Desktop računala,pc,kompjuteri,kompjutori",
                            Keywords = "",
                            Name = "Desktop-racunala",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 8,
                            DisplayName = "Laptopi",
                            Keywords = "",
                            Name = "Laptopi",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 8,
                            DisplayName = "Računalna oprema",
                            Keywords = "kompjuterska oprema",
                            Name = "Racunalna-oprema",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 8,
                            DisplayName = "Mobiteli",
                            Keywords = "mobilni telefoni",
                            Name = "Mobiteli",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 8,
                            DisplayName = "Punjači i oprema za mobitele",
                            Keywords = "",
                            Name = "Punjaci-oprema-mobiteli",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 8,
                            DisplayName = "Pametni satovi",
                            Keywords = "",
                            Name = "Pametni-satovi",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 8,
                            DisplayName = "Tableti",
                            Keywords = "",
                            Name = "Tableti",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 8,
                            DisplayName = "Ostalo - računala i mobiteli",
                            Keywords = "",
                            Name = "Ostalo-racunala-mobiteli",
                            ParentCategoryName = "Racunala-mobiteli"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 9,
                            DisplayName = "Konzole",
                            Keywords = "konzola",
                            Name = "Konzole",
                            ParentCategoryName = "Konzole-igrice"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 9,
                            DisplayName = "Videoigre",
                            Keywords = "igrice,videoigrice",
                            Name = "Videoigre",
                            ParentCategoryName = "Konzole-igrice"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 9,
                            DisplayName = "Oprema i dodaci",
                            Keywords = "",
                            Name = "Oprema-dodaci-konzole",
                            ParentCategoryName = "Konzole-igrice"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 10,
                            DisplayName = "Ženska odjeća",
                            Keywords = "Odjeca za zene,Odjeća za žene",
                            Name = "Zenska-odjeca",
                            ParentCategoryName = "Odjeca-obuca"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 10,
                            DisplayName = "Ženska obuća",
                            Keywords = "Obuca za zene,",
                            Name = "Zenska-obuca",
                            ParentCategoryName = "Odjeca-obuca"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 10,
                            DisplayName = "Muška odjeća",
                            Keywords = "",
                            Name = "Muska-odjeca",
                            ParentCategoryName = "Odjeca-obuca"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 10,
                            DisplayName = "Muška obuća",
                            Keywords = "",
                            Name = "Muska-obuca",
                            ParentCategoryName = "Odjeca-obuca"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 10,
                            DisplayName = "Dječja odjeća i obuća",
                            Keywords = "odjeca za djecu,odjeća za djecu",
                            Name = "Djecja-odjeca-obuca",
                            ParentCategoryName = "Odjeca-obuca"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 11,
                            DisplayName = "Nakit",
                            Keywords = "",
                            Name = "Nakit",
                            ParentCategoryName = "Nakit-satovi"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 11,
                            DisplayName = "Ručni satovi",
                            Keywords = "",
                            Name = "Rucni-satovi",
                            ParentCategoryName = "Nakit-satovi"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 11,
                            DisplayName = "Zidni satovi",
                            Keywords = "",
                            Name = "Zidni-satovi",
                            ParentCategoryName = "Nakit-satovi"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 11,
                            DisplayName = "Broševi i bedževi",
                            Keywords = "",
                            Name = "Brosevi-bedzevi",
                            ParentCategoryName = "Nakit-satovi"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 11,
                            DisplayName = "Drago kamenje",
                            Keywords = "",
                            Name = "Drago-kamenje",
                            ParentCategoryName = "Nakit-satovi"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 11,
                            DisplayName = "Ostalo - nakit i satovi",
                            Keywords = "",
                            Name = "Ostalo-nakit-satovi",
                            ParentCategoryName = "Nakit-satovi"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 12,
                            DisplayName = "Torbice",
                            Keywords = "torbe,neseseri,tašne,tasne,tasnice,tašnice",
                            Name = "Torbice",
                            ParentCategoryName = "Modni-dodaci"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 12,
                            DisplayName = "Naočale",
                            Keywords = "",
                            Name = "Naocale",
                            ParentCategoryName = "Modni-dodaci"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 12,
                            DisplayName = "Kaiševi",
                            Keywords = "remenovi,remeni,remenje",
                            Name = "Kaisevi",
                            ParentCategoryName = "Modni-dodaci"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 12,
                            DisplayName = "Novčanici",
                            Keywords = "",
                            Name = "Novcanici",
                            ParentCategoryName = "Modni-dodaci"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 12,
                            DisplayName = "Ostalo - modni dodaci",
                            Keywords = "",
                            Name = "Ostalo-modni-dodaci",
                            ParentCategoryName = "Modni-dodaci"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 13,
                            DisplayName = "Kozmetika i šminka",
                            Keywords = "maskare,maskara,puderi,ruzevi,ruževi,karmini",
                            Name = "Kozmetika-sminka",
                            ParentCategoryName = "Ljepota-zdravlje"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 13,
                            DisplayName = "Njega kose i tijela",
                            Keywords = "samponi,šamponi,ulja,gelovi",
                            Name = "Njega-kose-tijela",
                            ParentCategoryName = "Ljepota-zdravlje"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 13,
                            DisplayName = "Parfemi",
                            Keywords = "mirisi",
                            Name = "Parfemi",
                            ParentCategoryName = "Ljepota-zdravlje"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 13,
                            DisplayName = "Zdravlje",
                            Keywords = "",
                            Name = "Zdravlje",
                            ParentCategoryName = "Ljepota-zdravlje"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 13,
                            DisplayName = "Ostalo - ljepota i zdravlje",
                            Keywords = "",
                            Name = "Ostalo-ljepota-zdravlje",
                            ParentCategoryName = "Ljepota-zdravlje"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 14,
                            DisplayName = "Sportska odjeća i obuća - žene",
                            Keywords = "",
                            Name = "Sportska-odjeca-obuca-zene",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 14,
                            DisplayName = "Sportska odjeća i obuća - muški",
                            Keywords = "",
                            Name = "Sportska-odjeca-obuca-muski",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 14,
                            DisplayName = "Sportovi s loptom",
                            Keywords = "",
                            Name = "Sportovi-s-loptom",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 14,
                            DisplayName = "Vodeni sportovi",
                            Keywords = "",
                            Name = "Vodeni-sportovi",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 14,
                            DisplayName = "Zimski sportovi",
                            Keywords = "",
                            Name = "Zimski-sportovi",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 14,
                            DisplayName = "Fitness i trening",
                            Keywords = "",
                            Name = "Fitness-trening",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 14,
                            DisplayName = "Lov i ribolov",
                            Keywords = "",
                            Name = "Lov-ribolov",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 14,
                            DisplayName = "Bicikli, role, romobili",
                            Keywords = "bicikla",
                            Name = "Bicikli-role-romobili",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 14,
                            DisplayName = "Posteri",
                            Keywords = "",
                            Name = "Posteri",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 14,
                            DisplayName = "Ostalo - sport",
                            Keywords = "",
                            Name = "Ostalo-sport",
                            ParentCategoryName = "Sport-oprema"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 15,
                            DisplayName = "Namještaj",
                            Keywords = "",
                            Name = "Namjestaj",
                            ParentCategoryName = "Dom-vrt"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 15,
                            DisplayName = "Bijela tehnika",
                            Keywords = "",
                            Name = "Bijela-tehnika",
                            ParentCategoryName = "Dom-vrt"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 15,
                            DisplayName = "Alati i pribor",
                            Keywords = "",
                            Name = "Alati-pribor",
                            ParentCategoryName = "Dom-vrt"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 15,
                            DisplayName = "Rasvjeta i sigurnost",
                            Keywords = "",
                            Name = "Rasvjeta-sigurnost",
                            ParentCategoryName = "Dom-vrt"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 15,
                            DisplayName = "Sve za čišćenje",
                            Keywords = "",
                            Name = "Ciscenje",
                            ParentCategoryName = "Dom-vrt"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 15,
                            DisplayName = "Sve za vrt",
                            Keywords = "",
                            Name = "Vrt",
                            ParentCategoryName = "Dom-vrt"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 15,
                            DisplayName = "Ostalo - dom",
                            Keywords = "",
                            Name = "Ostalo-dom",
                            ParentCategoryName = "Dom-vrt"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 16,
                            DisplayName = "Akcijske figurice",
                            Keywords = "akcione figurice",
                            Name = "Akcijske-figurice",
                            ParentCategoryName = "Igre-igracke"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 16,
                            DisplayName = "Na baterije",
                            Keywords = "igračke na baterije,igracke na baterije",
                            Name = "Na-baterije",
                            ParentCategoryName = "Igre-igracke"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 16,
                            DisplayName = "Plišane igračke",
                            Keywords = "plišanci,plisane igracke",
                            Name = "Plisanci",
                            ParentCategoryName = "Igre-igracke"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 16,
                            DisplayName = "Lego i slaganje",
                            Keywords = "lego kockice,lego kocke",
                            Name = "Lego-slaganje",
                            ParentCategoryName = "Igre-igracke"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 16,
                            DisplayName = "Društvene igre",
                            Keywords = "",
                            Name = "Drustvene-igre",
                            ParentCategoryName = "Igre-igracke"
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 16,
                            DisplayName = "Ostalo - igre i igračke",
                            Keywords = "",
                            Name = "Ostalo-igracke",
                            ParentCategoryName = "Igre-igracke"
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 17,
                            DisplayName = "Školski pribor",
                            Keywords = "za školu,za skolu,skolski pribor",
                            Name = "Skolski-pribor",
                            ParentCategoryName = "Skola-posao"
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 17,
                            DisplayName = "Uredski pribor",
                            Keywords = "za posao,za ured",
                            Name = "Uredski-pribor",
                            ParentCategoryName = "Skola-posao"
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 18,
                            DisplayName = "Vozila i oprema",
                            Keywords = "auta,auti,automobili,motori,quadovi,kombiji,dzipovi,džipovi",
                            Name = "Vozila",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 18,
                            DisplayName = "Sve za bebe",
                            Keywords = "",
                            Name = "Za-bebe",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 18,
                            DisplayName = "Kućni ljubimci",
                            Keywords = "kucni,ljubimci,psi,mačke,macke",
                            Name = "Kucni-ljubimci",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 18,
                            DisplayName = "Maske",
                            Keywords = "",
                            Name = "Maske",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 18,
                            DisplayName = "Medicinska pomagala",
                            Keywords = "",
                            Name = "Medicinska-pomagala",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 18,
                            DisplayName = "Mjernoregulacijski instrumenti",
                            Keywords = "",
                            Name = "Mjernoregulacijski-instrumenti",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 18,
                            DisplayName = "Špijunska oprema",
                            Keywords = "",
                            Name = "Spijunska-oprema",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 18,
                            DisplayName = "Oprema za pušače",
                            Keywords = "",
                            Name = "Oprema-pusaci",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 18,
                            DisplayName = "Seksualna pomagala",
                            Keywords = "sex,porno",
                            Name = "Seksualna-pomagala",
                            ParentCategoryName = "Ostalo"
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 18,
                            DisplayName = "Ostalo - nesvrstano",
                            Keywords = "",
                            Name = "Ostalo-nesvrstano",
                            ParentCategoryName = "Ostalo"
                        });
                });

            modelBuilder.Entity("ecom.Models.Writer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowedProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTopTrader")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("RatingSum")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecom.Models.Product", b =>
                {
                    b.HasOne("ecom.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecom.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("ecom.Models.SubCategory", b =>
                {
                    b.HasOne("ecom.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ecom.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ecom.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
