// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecom.Data;

#nullable disable

namespace ecom.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ecom.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Kolekcionarstvo",
                            Keywords = "kolekcije,kolekcija",
                            Name = "Kolekcionarstvo",
                            Note = ""
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Numizmatika",
                            Keywords = "novac",
                            Name = "Numizmatika",
                            Note = ""
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Antikviteti",
                            Keywords = "starine",
                            Name = "Antikviteti",
                            Note = ""
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Umjetnost",
                            Keywords = "umjetnine",
                            Name = "Umjetnost",
                            Note = ""
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Knjige i tisak",
                            Keywords = "",
                            Name = "Knjige-tisak",
                            Note = ""
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Glazba i film",
                            Keywords = "",
                            Name = "Glazba-film",
                            Note = ""
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Audio / video",
                            Keywords = "multimedija,av tehnika, audio video tehnika, audio i video tehnika,a/v tehnika",
                            Name = "Audio-video",
                            Note = ""
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Računala i mobiteli",
                            Keywords = "",
                            Name = "Racunala-mobiteli",
                            Note = ""
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "Konzole i igrice",
                            Keywords = "igrice",
                            Name = "Konzole-igrice",
                            Note = ""
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "Odjeća i obuća",
                            Keywords = "",
                            Name = "Odjeca-obuca",
                            Note = ""
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "Nakit i satovi",
                            Keywords = "",
                            Name = "Nakit-satovi",
                            Note = ""
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "Modni dodaci",
                            Keywords = "accessories",
                            Name = "Modni-dodaci",
                            Note = ""
                        },
                        new
                        {
                            Id = 13,
                            DisplayName = "Ljepota i zdravlje",
                            Keywords = "",
                            Name = "Ljepota-zdravlje",
                            Note = ""
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "Sport i oprema",
                            Keywords = "sportska oprema",
                            Name = "Sport-oprema",
                            Note = ""
                        },
                        new
                        {
                            Id = 15,
                            DisplayName = "Dom i vrt",
                            Keywords = "za kuću,za kucu,za dom,kuća,stan,kuca",
                            Name = "Dom-vrt",
                            Note = ""
                        },
                        new
                        {
                            Id = 16,
                            DisplayName = "Igre i igračke",
                            Keywords = "igracke",
                            Name = "Igre-igracke",
                            Note = ""
                        },
                        new
                        {
                            Id = 17,
                            DisplayName = "Škola i posao",
                            Keywords = "",
                            Name = "Skola-posao",
                            Note = ""
                        },
                        new
                        {
                            Id = 18,
                            DisplayName = "Ostalo",
                            Keywords = "",
                            Name = "Ostalo",
                            Note = "Predmeti koji nemaju posebnu kategoriju."
                        });
                });

            modelBuilder.Entity("ecom.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ecom.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuctionStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasExtraPictures")
                        .HasColumnType("bit");

                    b.Property<string>("ImagesUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdvertised")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEndTimeAdjusted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStartTimeAdjusted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OfferCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ProdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("WriterId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ecom.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Militarija",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Militarija"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Filatelija",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Filatelija"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Keywords = "figure",
                            Name = "Figurice",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Figurice"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Keywords = "slicice,kartice,igraće karte,igrace karte",
                            Name = "Sličice, karte i albumi",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Slicice-karte-albumi"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Razglednice",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Razglednice"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Keywords = "modelarstvo,maketarstvo,autići,autici,modeli auta",
                            Name = "Modeli i makete",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Modeli-makete"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Suveniri",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Suveniri"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Keywords = "privesci,privjesci za ključeve,privjesci za kljuceve",
                            Name = "Privjesci",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Privjesci"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Ulaznice i karte",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Ulaznice-karte"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Telefonske kartice",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Telefonske-kartice"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Keywords = "trofeji,kolajne",
                            Name = "Pehari i medalje",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Pehari-medalje"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Keywords = "registracije,registarske tablice",
                            Name = "Registracijske tablice",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Registracijske-tablice"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Keywords = "zastavice",
                            Name = "Zastave",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Zastave"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Keywords = "salvetice",
                            Name = "Salvete",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Salvete"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Lotovi",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Lotovi"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Keywords = "",
                            Name = "Ostalo - kolekcionarstvo",
                            ParentCategoryName = "Kolekcionarstvo",
                            RouteName = "Ostalo-kolekcionarstvo"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Keywords = "novčići,novcici",
                            Name = "Kovanice",
                            ParentCategoryName = "Numizmatika",
                            RouteName = "Kovanice"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Keywords = "novcanice",
                            Name = "Novčanice",
                            ParentCategoryName = "Numizmatika",
                            RouteName = "Novcanice"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Keywords = "",
                            Name = "Bonovi",
                            ParentCategoryName = "Numizmatika",
                            RouteName = "Bonovi"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Keywords = "",
                            Name = "Žetoni",
                            ParentCategoryName = "Numizmatika",
                            RouteName = "Zetoni"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Keywords = "",
                            Name = "Ostalo - numizmatika",
                            ParentCategoryName = "Numizmatika",
                            RouteName = "Ostalo-numizmatika"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Keywords = "",
                            Name = "Keramika, porculan i staklo",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Keramika-porculan-staklo"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Keywords = "starinski",
                            Name = "Stari namještaj",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Stari-namjestaj"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Keywords = "",
                            Name = "Stari uređaji i aparati",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Stari-uredaji-aparati"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Keywords = "",
                            Name = "Stari pribor i oprema",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Stari-pribor-oprema"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Keywords = "",
                            Name = "Stara odjeća i obuća",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Stara-odjeca-obuca"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Keywords = "starinski nakit",
                            Name = "Stari nakit i satovi",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Stari-nakit-satovi"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Keywords = "",
                            Name = "Stare knjige i dokumenti",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Stare-knjige-dokumenti"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Keywords = "",
                            Name = "Ostalo - antikviteti",
                            ParentCategoryName = "Antikviteti",
                            RouteName = "Ostalo-antikviteti"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Keywords = "",
                            Name = "Umjetničke slike",
                            ParentCategoryName = "Umjetnost",
                            RouteName = "Umjetnicke-slike"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Keywords = "",
                            Name = "Fotografije",
                            ParentCategoryName = "Umjetnost",
                            RouteName = "Fotografije"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Keywords = "",
                            Name = "Ikone",
                            ParentCategoryName = "Umjetnost",
                            RouteName = "Ikone"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Keywords = "",
                            Name = "Skulpture",
                            ParentCategoryName = "Umjetnost",
                            RouteName = "Skulpture"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Keywords = "",
                            Name = "Gobleni",
                            ParentCategoryName = "Umjetnost",
                            RouteName = "Gobleni"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Keywords = "",
                            Name = "Ostalo - umjetnost",
                            ParentCategoryName = "Umjetnost",
                            RouteName = "Ostalo-umjetnost"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 5,
                            Keywords = "",
                            Name = "Književnost",
                            ParentCategoryName = "Knjige-tisak",
                            RouteName = "Knjizevnost"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Keywords = "",
                            Name = "Znanost i enciklopedije",
                            ParentCategoryName = "Knjige-tisak",
                            RouteName = "Znanost-enciklopedije"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            Keywords = "",
                            Name = "Atlasi i karte",
                            ParentCategoryName = "Knjige-tisak",
                            RouteName = "Atlasi-karte"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Keywords = "",
                            Name = "Magazini i časopisi",
                            ParentCategoryName = "Knjige-tisak",
                            RouteName = "Magazini-casopisi"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Keywords = "",
                            Name = "Stripovi",
                            ParentCategoryName = "Knjige-tisak",
                            RouteName = "Stripovi"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Keywords = "",
                            Name = "Dječja literatura",
                            ParentCategoryName = "Knjige-tisak",
                            RouteName = "Djecja-literatura"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Keywords = "",
                            Name = "Ostalo - tisak",
                            ParentCategoryName = "Knjige-tisak",
                            RouteName = "Ostalo-tisak"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 6,
                            Keywords = "muzički,instrumenti",
                            Name = "Glazbeni instrumenti",
                            ParentCategoryName = "Glazba-film",
                            RouteName = "Glazbeni-instrumenti"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            Keywords = "",
                            Name = "CDovi",
                            ParentCategoryName = "Glazba-film",
                            RouteName = "CDovi"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            Keywords = "",
                            Name = "Audio kasete",
                            ParentCategoryName = "Glazba-film",
                            RouteName = "Audio-Kasete"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            Keywords = "",
                            Name = "Gramofonske ploče",
                            ParentCategoryName = "Glazba-film",
                            RouteName = "Gramofonske-ploce"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            Keywords = "",
                            Name = "DVD i BluRay",
                            ParentCategoryName = "Glazba-film",
                            RouteName = "DVD-BluRay"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 6,
                            Keywords = "",
                            Name = "VHS",
                            ParentCategoryName = "Glazba-film",
                            RouteName = "VHS"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 6,
                            Keywords = "",
                            Name = "Ostalo - glazba i film",
                            ParentCategoryName = "Glazba-film",
                            RouteName = "Ostalo-glazba-film"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 7,
                            Keywords = "Televizori",
                            Name = "TV i oprema",
                            ParentCategoryName = "Audio-video",
                            RouteName = "TV-oprema"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            Keywords = "",
                            Name = "Fotoaparati i kamere",
                            ParentCategoryName = "Audio-video",
                            RouteName = "Fotoaparati-kamere"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 7,
                            Keywords = "",
                            Name = "Dronovi",
                            ParentCategoryName = "Audio-video",
                            RouteName = "Dronovi"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 7,
                            Keywords = "radioprijemnik,radioprijemnici",
                            Name = "Radio i telefoni",
                            ParentCategoryName = "Audio-video",
                            RouteName = "Radio-telefoni"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 7,
                            Keywords = "zvučnik,pojačalo",
                            Name = "Zvučnici i pojačala",
                            ParentCategoryName = "Audio-video",
                            RouteName = "Zvucnici-pojacala"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 7,
                            Keywords = "kazetofoni",
                            Name = "Linije i kasetofoni",
                            ParentCategoryName = "Audio-video",
                            RouteName = "Linije-kasetofoni"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 7,
                            Keywords = "kućno kino",
                            Name = "Kućna kina i DVD playeri",
                            ParentCategoryName = "Audio-video",
                            RouteName = "Kucno-kino-dvd-playeri"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 7,
                            Keywords = "mp3 playeri",
                            Name = "MP3, walkmani, iPodi",
                            ParentCategoryName = "Audio-video",
                            RouteName = "MP3-walkman-ipod"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 7,
                            Keywords = "",
                            Name = "Ostalo - audio / video",
                            ParentCategoryName = "Audio-video",
                            RouteName = "Ostalo-audio-video"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 8,
                            Keywords = "PC, kompjuteri, kompjutori",
                            Name = "Desktop računala",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Desktop-racunala"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 8,
                            Keywords = "",
                            Name = "Laptopi",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Laptopi"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 8,
                            Keywords = "kompjuterska oprema",
                            Name = "Računalna oprema",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Racunalna-oprema"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 8,
                            Keywords = "mobilni telefoni",
                            Name = "Mobiteli",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Mobiteli"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 8,
                            Keywords = "",
                            Name = "Punjači i oprema za mobitele",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Punjaci-oprema-mobiteli"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 8,
                            Keywords = "",
                            Name = "Pametni satovi",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Pametni-satovi"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 8,
                            Keywords = "",
                            Name = "Tableti",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Tableti"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 8,
                            Keywords = "",
                            Name = "Ostalo - računala i mobiteli",
                            ParentCategoryName = "Racunala-mobiteli",
                            RouteName = "Ostalo-racunala-mobiteli"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 9,
                            Keywords = "konzola",
                            Name = "Konzole",
                            ParentCategoryName = "Konzole-igrice",
                            RouteName = "Konzole"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 9,
                            Keywords = "igrice,videoigrice",
                            Name = "Videoigre",
                            ParentCategoryName = "Konzole-igrice",
                            RouteName = "Videoigre"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 9,
                            Keywords = "",
                            Name = "Oprema i dodaci",
                            ParentCategoryName = "Konzole-igrice",
                            RouteName = "Oprema-dodaci-konzole"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 10,
                            Keywords = "Odjeca za zene,Odjeća za žene",
                            Name = "Ženska odjeća",
                            ParentCategoryName = "Odjeca-obuca",
                            RouteName = "Zenska-odjeca"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 10,
                            Keywords = "Obuca za zene,",
                            Name = "Ženska obuća",
                            ParentCategoryName = "Odjeca-obuca",
                            RouteName = "Zenska-obuca"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 10,
                            Keywords = "",
                            Name = "Muška odjeća",
                            ParentCategoryName = "Odjeca-obuca",
                            RouteName = "Muska-odjeca"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 10,
                            Keywords = "",
                            Name = "Muška obuća",
                            ParentCategoryName = "Odjeca-obuca",
                            RouteName = "Muska-obuca"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 10,
                            Keywords = "odjeca za djecu,odjeća za djecu",
                            Name = "Dječja odjeća i obuća",
                            ParentCategoryName = "Odjeca-obuca",
                            RouteName = "Djecja-odjeca-obuca"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 11,
                            Keywords = "",
                            Name = "Nakit",
                            ParentCategoryName = "Nakit-satovi",
                            RouteName = "Nakit"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 11,
                            Keywords = "",
                            Name = "Ručni satovi",
                            ParentCategoryName = "Nakit-satovi",
                            RouteName = "Rucni-satovi"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 11,
                            Keywords = "",
                            Name = "Zidni satovi",
                            ParentCategoryName = "Nakit-satovi",
                            RouteName = "Zidni-satovi"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 11,
                            Keywords = "",
                            Name = "Broševi i bedževi",
                            ParentCategoryName = "Nakit-satovi",
                            RouteName = "Brosevi-bedzevi"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 11,
                            Keywords = "",
                            Name = "Drago kamenje",
                            ParentCategoryName = "Nakit-satovi",
                            RouteName = "Drago-kamenje"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 11,
                            Keywords = "",
                            Name = "Ostalo - nakit i satovi",
                            ParentCategoryName = "Nakit-satovi",
                            RouteName = "Ostalo-nakit-satovi"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 12,
                            Keywords = "torbe,neseseri,tašne,tasne,tasnice,tašnice",
                            Name = "Torbice",
                            ParentCategoryName = "Modni-dodaci",
                            RouteName = "Torbice"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 12,
                            Keywords = "",
                            Name = "Naočale",
                            ParentCategoryName = "Modni-dodaci",
                            RouteName = "Naocale"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 12,
                            Keywords = "remenovi,remeni,remenje",
                            Name = "Kaiševi",
                            ParentCategoryName = "Modni-dodaci",
                            RouteName = "Kaisevi"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 12,
                            Keywords = "",
                            Name = "Novčanici",
                            ParentCategoryName = "Modni-dodaci",
                            RouteName = "Novcanici"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 12,
                            Keywords = "",
                            Name = "Ostalo - modni dodaci",
                            ParentCategoryName = "Modni-dodaci",
                            RouteName = "Ostalo-modni-dodaci"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 13,
                            Keywords = "maskare,maskara,puderi,ruzevi,ruževi,karmini",
                            Name = "Kozmetika i šminka",
                            ParentCategoryName = "Ljepota-zdravlje",
                            RouteName = "Kozmetika-sminka"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 13,
                            Keywords = "samponi,šamponi,ulja,gelovi",
                            Name = "Njega kose i tijela",
                            ParentCategoryName = "Ljepota-zdravlje",
                            RouteName = "Njega-kose-tijela"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 13,
                            Keywords = "mirisi",
                            Name = "Parfemi",
                            ParentCategoryName = "Ljepota-zdravlje",
                            RouteName = "Parfemi"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 13,
                            Keywords = "",
                            Name = "Zdravlje",
                            ParentCategoryName = "Ljepota-zdravlje",
                            RouteName = "Zdravlje"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 13,
                            Keywords = "",
                            Name = "Ostalo - ljepota i zdravlje",
                            ParentCategoryName = "Ljepota-zdravlje",
                            RouteName = "Ostalo-ljepota-zdravlje"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Sportska odjeća i obuća - žene",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Sportska-odjeca-obuca-zene"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Sportska odjeća i obuća - muški",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Sportska-odjeca-obuca-muski"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Sportovi s loptom",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Sportovi-s-loptom"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Vodeni sportovi",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Vodeni-sportovi"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Zimski sportovi",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Zimski-sportovi"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Fitness i trening",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Fitness-trening"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Lov i ribolov",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Lov-ribolov"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 14,
                            Keywords = "bicikla",
                            Name = "Bicikli, role, romobili",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Bicikli-role-romobili"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Posteri",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Posteri"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 14,
                            Keywords = "",
                            Name = "Ostalo - sport",
                            ParentCategoryName = "Sport-oprema",
                            RouteName = "Ostalo-sport"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 15,
                            Keywords = "",
                            Name = "Namještaj",
                            ParentCategoryName = "Dom-vrt",
                            RouteName = "Namjestaj"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 15,
                            Keywords = "",
                            Name = "Bijela tehnika",
                            ParentCategoryName = "Dom-vrt",
                            RouteName = "Bijela-tehnika"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 15,
                            Keywords = "",
                            Name = "Alati i pribor",
                            ParentCategoryName = "Dom-vrt",
                            RouteName = "Alati-pribor"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 15,
                            Keywords = "",
                            Name = "Rasvjeta i sigurnost",
                            ParentCategoryName = "Dom-vrt",
                            RouteName = "Rasvjeta-sigurnost"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 15,
                            Keywords = "",
                            Name = "Sve za čišćenje",
                            ParentCategoryName = "Dom-vrt",
                            RouteName = "Ciscenje"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 15,
                            Keywords = "",
                            Name = "Sve za vrt",
                            ParentCategoryName = "Dom-vrt",
                            RouteName = "Vrt"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 15,
                            Keywords = "",
                            Name = "Ostalo - dom",
                            ParentCategoryName = "Dom-vrt",
                            RouteName = "Ostalo-dom"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 16,
                            Keywords = "akcione figurice",
                            Name = "Akcijske figurice",
                            ParentCategoryName = "Igre-igracke",
                            RouteName = "Akcijske-figurice"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 16,
                            Keywords = "igračke na baterije,igracke na baterije",
                            Name = "Na baterije",
                            ParentCategoryName = "Igre-igracke",
                            RouteName = "Na-baterije"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 16,
                            Keywords = "plišanci,plisane igracke",
                            Name = "Plišane igračke",
                            ParentCategoryName = "Igre-igracke",
                            RouteName = "Plisanci"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 16,
                            Keywords = "lego kockice,lego kocke",
                            Name = "Lego i slaganje",
                            ParentCategoryName = "Igre-igracke",
                            RouteName = "Lego-slaganje"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 16,
                            Keywords = "",
                            Name = "Društvene igre",
                            ParentCategoryName = "Igre-igracke",
                            RouteName = "Drustvene-igre"
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 16,
                            Keywords = "",
                            Name = "Ostalo - igre i igračke",
                            ParentCategoryName = "Igre-igracke",
                            RouteName = "Ostalo-igracke"
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 17,
                            Keywords = "za školu,za skolu,skolski pribor",
                            Name = "Školski pribor",
                            ParentCategoryName = "Skola-posao",
                            RouteName = "Skolski-pribor"
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 17,
                            Keywords = "za posao,za ured",
                            Name = "Uredski pribor",
                            ParentCategoryName = "Skola-posao",
                            RouteName = "Uredski-pribor"
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 18,
                            Keywords = "auta,auti,automobili,motori,quadovi,kombiji,dzipovi,džipovi",
                            Name = "Vozila i oprema",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Vozila"
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 18,
                            Keywords = "",
                            Name = "Sve za bebe",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Za-bebe"
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 18,
                            Keywords = "kucni,ljubimci,psi,mačke,macke",
                            Name = "Kućni ljubimci",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Kucni-ljubimci"
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 18,
                            Keywords = "",
                            Name = "Maske",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Maske"
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 18,
                            Keywords = "",
                            Name = "Medicinska pomagala",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Medicinska-pomagala"
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 18,
                            Keywords = "",
                            Name = "Mjernoregulacijski instrumenti",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Mjernoregulacijski-instrumenti"
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 18,
                            Keywords = "",
                            Name = "Špijunska oprema",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Spijunska-oprema"
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 18,
                            Keywords = "",
                            Name = "Oprema za pušače",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Oprema-pusaci"
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 18,
                            Keywords = "sex,porno",
                            Name = "Seksualna pomagala",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Seksualna-pomagala"
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 18,
                            Keywords = "",
                            Name = "Ostalo - nesvrstano",
                            ParentCategoryName = "Ostalo",
                            RouteName = "Ostalo-nesvrstano"
                        });
                });

            modelBuilder.Entity("ecom.Models.Writer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowedProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTopTrader")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("RatingSum")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ecom.Models.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecom.Models.Product", b =>
                {
                    b.HasOne("ecom.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecom.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ecom.Models.Writer", "Writer")
                        .WithMany("Products")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("ecom.Models.SubCategory", b =>
                {
                    b.HasOne("ecom.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ecom.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ecom.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ecom.Models.Writer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
